# Generated by Django 4.0.3 on 2022-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('Discount', models.IntegerField(default=0)),
                ('Duration', models.FloatField()),
                ('Authorname', models.CharField(max_length=100)),
            ],
        ),
    ]
