# Generated by Django 4.0.3 on 2022-03-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBVapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CBVCourse',
        ),
    ]
