# Generated by Django 4.0.3 on 2022-03-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
