# Generated by Django 4.0.3 on 2022-03-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_user_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='username',
        ),
    ]
